### DISCUSSION TITLE
GSoC 2022: Custom file

### DISCUSSION THREAD

**Discussion by xRay2016** [pgexporter/pgexporter#36] [Ideas]
Hi all!😀

I am Donglin Xie. I am glad to be the GSoC2022 contributor this year!
Here is my proposal for pgexporter!

## Project Description📌
In this project, we will add the option to have a custom query file to specify the queries run against the 
PostgreSQL instances.

## Design Ideas💡
1. The format of custom file may be like this. It define the specific custom queries. I think I should learn the meaning of the type "gauge" and "counter". The prometheus has four core metrics types. [https://prometheus.io/docs/concepts/metric_types/](url). The implementations for different type may varies.
``` 
  -
    query: SELECT ...
    tag: postgresql_primary
    server: primary | both | replica
    sort: name | data
    columns:
      - 
        description: ......
        name: ......
        type: gauge | counter | histogram | label 

``` 

2. The custom query file is parsed in the startup phase, and run each time pgexporter is invoked. Therefore, the custom file path may be a argument of program. If the command specify that, it will parsed into some struct to represent the custom  queries.

3. In the metrics_page() function, if there is any custom queries, the result of custom queries is send to the client socket.   

Welcome any suggestions and discussions!😀

## Result :paperclip:
1. [Custom metrics](https://github.com/pgexporter/pgexporter/commit/7fccd7e96fe21d2a3ef2eea3bec1d8ba2d006bf1)
2. [Server type filter](https://github.com/pgexporter/pgexporter/commit/5e2a5e1c5f91aecc3bcd07949c8c0405f56e6b98)
3. [YAML options](https://github.com/pgexporter/pgexporter/commit/e0cc08ad97dc4b6f0265dcf0077e18f757544150)
4. [Histogram support]()

Related issue [#40 ]

The tutorial of my work is in [02_custom_metrics.md](https://github.com/xRay2016/pgexporter/blob/dev4/doc/tutorial/02_custom_metrics.md) now.

**Comment by jesperpedersen** [comment]
Welcome !

I think using a YAML format is ok, and then parsing it into a list of `struct`s that are executed. I think the core metrics should always be executed even with the YAML file enabled.

An idea could be to take the existing metrics - except core - and use them as a `contrib/metrics/postgresql-10.yaml` file as a Proof-of-Concept. Then it is easy to create `-11`, `-12`, `-13`, `-14` and `-15` files from that.

https://github.com/yaml/libyaml looks like a good starting point.

**Reply by xRay2016** [reply]
Thanks for the suggestions! 😀 
The parse of YAML file should be a good start pointing. I will have a try.

**Comment by xRay2016** [comment]
The format of *Promethues* output is as follows:
``` c
<metric name>{<label name>=<label value>, ...} value
```

Acoording to the format, I design the metric struct and the yaml format. The definition of metric is as follow:
``` c++
typedef struct Metric
{
    int type;                           //metrics type 0--counter 1--gauge
    char query_str[MAX_QUERY_LENGTH];   //query string
    char tag[MISC_LENGTH];              //tag name
    int columns;                        //the number of columns in result
} Metric;
```
The *yaml* file is like this:
``` yaml
# database_information()
  -
    type: gauge
    query: SELECT datname, pg_database_size(datname) FROM pg_database;
    tag: pg_database
    columns: 2

# replication_information()
  -
    type: gauge
    query: SELECT slot_name,active FROM pg_replication_slots;
    tag: pg_replication_slots
    columns: 2
```
Every object in *yaml* is used to represent one metric. There maybe multi columns in result. I make the assumptionThe that the last column in the result is the value and other values are used as label of metrics. For example, the *replication_information()* includes two columns. The first column is *slot_name*, so the *Promethues* output will be like this:
```c++
pg_replication_slots{server="server_name", slot_name=""} value
```

This week, I am working on the parser of *metrics.yaml*. Currently, it could read out the *yaml* file  and parse it to the array of *metric*. 

Welcome any suggestions and discussions!😀

**Reply by jesperpedersen** [reply]
Yeah, we something flexible such that people can design their own layout.

Maybe

```
# replication_information()
  -
    query: SELECT slot_name,active,temporary FROM pg_replication_slots;
    metric: pg_replication_slots
    columns:
    - column:
      name: slot_name
      type: label 
    - column:
      description: Is the replication active
      name: active
      type: gauge
    - column:
      description: Is the replication temporary
      name: temporary
      type: gauge
```

would translate into

```
#HELP pg_replication_slots_active Is the replication active
#TYPE pg_replication_slots_active gauge
pg_replication_slots_active{server="replica",slot_name="replica"} 1

#HELP pg_replication_slots_temporary Is the replication temporary
#TYPE pg_replication_slots_temporary gauge
pg_replication_slots_temporary{server="replica",slot_name="replica"} 0
```

So `label`s would go into each `counter` or `gauge` entry (`server` is always present).

Thoughts ?
