### ISSUE TITLE
Version Support for PostgreSQL extensions

### ISSUE THREAD

**Issue by resyfer** [pgexporter/pgexporter#106]

**Comment by resyfer** [comment]
### Config
Considering each server may have their own version of an extension independent of others, I think the following syntax in YAML would do for this task:

```yml
version: ...
metrics:
  - queries:
    - query: "Query 1"
      version: 14 # Version For PostgreSQL
      extensions:
        - name: "extension1"
          version: 1.0
        - name: "extension2"
          version: 2.5
    - query: "Query 2"
      version: 16 # Version For PostgreSQL
      extensions:
        - name: "extension1"
          version: 1.5
        - name: "extension2"
          version: 4.5
      
```

Where for the following values of postgresql version, extension1 version and extension2 version, the corresponding queries will be sent:

|PostgreSQL Version|Extension1 Version|Extension2 Version|Query Sent|
|---|---|---|---|
|14|1.3|2.5|Query 1|
|16|1.2|5|**Undetermined**|
|16|1.2|4|Query 1|
|16|2.5|5|Query 2|

### Problem
As a side note, this would make the logic significantly more complex as it needs to look into:
- Comparing versions that may or may not follow a certain standard (eg. semver).
- Undetermined cases like shown above...since if Query 1 is sent, there may be a chance that Extension2 might not support the query, and if Query 2 is sent, both PostgreSQL 14 and Extension1 may not support it.

### Solution
The only solution I can see is to only compare PostgreSQL versions for `>=` or `<=`, but only `==` or `!=` when it comes to extension versions and treat them as strings rather than, say, a version structure that enables comparison.
