### ISSUE TITLE
Extension Version Field

### ISSUE THREAD

**Issue by bassamadnan** [pgexporter/pgexporter#229]
We need to build on top of the existing YAML format and add fields for extension version to load queries. This also means we need to implement a semantic versioning logic, maybe in a new `semvar.h` or in utils

**Comment by jesperpedersen** [comment]
@bassamadnan I don't think we can use the existing YAML for this - so think about a new format that are specific for extensions - delta format, or all-in one

**Comment by jesperpedersen** [comment]
@bassamadnan I don't think we need `tag` and `collector` for the extension format. We should just need a `metric` as the name for each query. We can get the prefix from the `struct extension`

**Comment by bassamadnan** [comment]
> @bassamadnan I don't think we need `tag` and `collector` for the extension format. We should just need a `metric` as the name for each query. We can get the prefix from the `struct extension`

Yes, that makes sense

**Comment by bassamadnan** [comment]
@jesperpedersen After recent discussions lets go with this format?
```yaml
extension: pg_stat_statements
metrics:
 - metric: queries
   queries:
     - query: SELECT queryid, calls FROM pg_stat_statements;
       version: "1.7"
       columns: [...]
     - query: SELECT queryid, calls, total_exec_time FROM pg_stat_statements;
       version: "1.8"
       columns: [...]
       
 - metric: database_stats
   queries:
     - query: SELECT dbname, calls FROM pg_stat_statements_db;
       version: "1.8"
       columns: [...]
```
Then in prometheus they would look like this 
```
pgexporter_pg_stat_statements_queries{...}
pgexporter_pg_stat_statements_database_stats{...}
```
