### ISSUE TITLE
/metrics endpoint exposition format is incorrect: metrics names include a mix of underscores & dots

### ISSUE THREAD

**Issue by nikitabugrovsky** [pgexporter/pgexporter#25]
**Describe the bug**

Prometheus v2.25.2 is unable to parse data provided by pgexporter `/metrics` endpoint. Scrape job fails with the following error:
` strconv.ParseFloat: parsing ".max": invalid syntax` & `  strconv.ParseFloat: parsing " not": invalid syntax`

**To Reproduce**

Steps to reproduce the behavior.
1. bin/pgexporter -c /etc/pgexporter/pgexporter.conf -u /etc/pgexporter/pgexporter_users.conf
2. make sure `/metrics` endpoint is up & running
3. Prometheus scrape job should be configured as follows:
```
- job_name: database-http-metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - <some_host>
    labels:
      env: stage
```

**Version**

What is the version of pgexporter ?

pgexporter 0.2.0

**Prometheus**

Can you provide the output of the invalid Prometheus metrics ?

Sample output:
```
#HELP pgexporter_pg_settings_pg_stat_statements.max Sets the maximum number of statements tracked by pg_stat_statements.
#TYPE pgexporter_pg_settings_pg_stat_statements.max gauge
pgexporter_pg_settings_pg_stat_statements.max{server="primary"} 5000
pgexporter_pg_settings_pg_stat_statements.max{server="replica"} 5000
pgexporter_pg_settings_pg_stat_statements.max{server="cascade"} 5000
```
